"use client";

import { useState } from "react";
import { CheckCircle2, X, BarChart3, GitBranch, Zap, Shield, Download, FlaskConical } from "lucide-react";
import { AnalysisReport } from "../../types/analysis";
import ComplexityTab from "./ComplexityTab";
import SimilarityTab from "./SimilarityTab";
import TimeTab from "./TimeTab";
import PracticesTab from "./PracticesTab";
import TestsTab from "./TestsTab";

type Tab = "complexity" | "similarity" | "time" | "practices" | "tests";

const TABS: { id: Tab; label: string; Icon: React.ElementType }[] = [
  { id: "complexity", label: "Cyclomatic", Icon: BarChart3 },
  { id: "similarity", label: "Duplicates", Icon: GitBranch },
  { id: "time", label: "Time Complexity", Icon: Zap },
  { id: "practices", label: "Bad Practices", Icon: Shield },
  { id: "tests", label: "Tests", Icon: FlaskConical },
];

function generateMarkdownReport(repoName: string, report: AnalysisReport): string {
  const date = new Date().toISOString().split("T")[0];
  const totalIssues = report.bad_practices.reduce((s, f) => s + f.issues.length, 0);
  const highComplexity = report.cyclomatic_complexity
    .flatMap((f) => f.functions)
    .filter((fn) => fn.complexity > 10).length;

  const lines: string[] = [
    `# CodeScope Analysis Report`,
    `**Repository:** ${repoName}`,
    `**Generated:** ${date}`,
    ``,
    `## Summary`,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Files analyzed | ${report.cyclomatic_complexity.length} |`,
    `| High-complexity functions (CC > 10) | ${highComplexity} |`,
    `| Duplicate file pairs | ${report.similarity_matrix.length} |`,
    `| Bad practice issues | ${totalIssues} |`,
    ``,
    `---`,
    ``,
    `## 1. Cyclomatic Complexity`,
    ``,
  ];

  for (const file of report.cyclomatic_complexity) {
    lines.push(`### ${file.file_path.split("/").pop()}`);
    lines.push(`\`${file.file_path}\``);
    if (file.functions.length) {
      lines.push(`| Function | CC | Line |`);
      lines.push(`|----------|----|------|`);
      for (const fn of file.functions) {
        const flag = fn.complexity > 10 ? " ⚠️" : fn.complexity > 5 ? " ⚡" : "";
        lines.push(`| \`${fn.name}\` | ${fn.complexity}${flag} | ${fn.lineno} |`);
      }
    } else {
      lines.push(`_No functions found_`);
    }
    lines.push(``);
  }

  lines.push(`---`, ``, `## 2. Duplicate Detection (TF-IDF Similarity)`, ``);
  if (report.similarity_matrix.length) {
    lines.push(`| File A | File B | Similarity |`);
    lines.push(`|--------|--------|-----------|`);
    for (const sim of report.similarity_matrix) {
      lines.push(
        `| \`${sim.file_pair[0].split("/").pop()}\` | \`${sim.file_pair[1].split("/").pop()}\` | ${(sim.similarity * 100).toFixed(1)}% |`
      );
    }
  } else {
    lines.push(`_Not enough files to compare_`);
  }

  lines.push(``, `---`, ``, `## 3. Time Complexity`, ``);
  for (const file of report.time_complexity) {
    lines.push(`### ${file.file_path.split("/").pop()}`);
    if (file.functions.length) {
      lines.push(`| Function | Complexity | Recursive | Line |`);
      lines.push(`|----------|-----------|-----------|------|`);
      for (const fn of file.functions) {
        lines.push(`| \`${fn.name}\` | ${fn.complexity} | ${fn.is_recursive ? "Yes" : "No"} | ${fn.lineno} |`);
      }
    } else {
      lines.push(`_No functions found_`);
    }
    lines.push(``);
  }

  lines.push(`---`, ``, `## 4. Bad Practices`, ``);
  const filesWithIssues = report.bad_practices.filter((f) => f.issues.length);
  if (filesWithIssues.length) {
    for (const file of filesWithIssues) {
      lines.push(`### ${file.file_path.split("/").pop()}`);
      lines.push(`| Line | Type | Message |`);
      lines.push(`|------|------|---------|`);
      for (const issue of file.issues) {
        lines.push(`| L${issue.line} | \`${issue.type}\` | ${issue.message} |`);
      }
      lines.push(``);
    }
  } else {
    lines.push(`✅ No bad practices detected`);
  }

  lines.push(``, `---`, ``, `## 5. Test Coverage`, ``);
  if (report.test_coverage.has_tests) {
    lines.push(`✅ **${report.test_coverage.test_count} test file(s) found**`, ``);
    lines.push(`| Test File |`, `|-----------|`);
    for (const fp of report.test_coverage.test_files) {
      lines.push(`| \`${fp.split("/").slice(-2).join("/")}\` |`);
    }
  } else {
    lines.push(`❌ **No tests found.** Consider adding test files matching \`test_*.py\` or \`*_test.py\`.`);
  }

  lines.push(``, `---`, `_Generated by [CodeScope](http://localhost:3000)_`);
  return lines.join("\n");
}

function downloadFile(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

interface Props {
  repoName: string;
  report: AnalysisReport;
  onClose: () => void;
}

export default function ReportViewer({ repoName, report, onClose }: Props) {
  const [activeTab, setActiveTab] = useState<Tab>("complexity");

  const handleDownload = () => {
    const md = generateMarkdownReport(repoName, report);
    downloadFile(md, `${repoName}-analysis.md`, "text/markdown");
  };

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex items-center gap-3 p-4 rounded-xl bg-slate-900/60 border border-slate-800">
        <CheckCircle2 className="w-5 h-5 text-green-400 shrink-0" />
        <div className="min-w-0 flex-1">
          <p className="font-semibold text-white truncate">{repoName}</p>
          <p className="text-xs text-slate-500">
            {report.cyclomatic_complexity.length} file(s) analyzed
          </p>
        </div>
        <button
          onClick={handleDownload}
          title="Download Markdown report"
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm bg-indigo-600 hover:bg-indigo-500 text-white transition-colors"
        >
          <Download className="w-3.5 h-3.5" />
          <span className="hidden sm:block">Report</span>
        </button>
        <button
          onClick={onClose}
          className="p-1.5 rounded-lg text-slate-500 hover:text-slate-300 hover:bg-slate-800 transition-colors"
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 p-1 bg-slate-900 rounded-xl border border-slate-800">
        {TABS.map(({ id, label, Icon }) => (
          <button
            key={id}
            onClick={() => setActiveTab(id)}
            className={[
              "flex-1 flex items-center justify-center gap-1.5 py-2 px-3 rounded-lg text-sm font-medium transition-all",
              activeTab === id ? "bg-indigo-600 text-white shadow" : "text-slate-400 hover:text-slate-200",
            ].join(" ")}
          >
            <Icon className="w-3.5 h-3.5" />
            <span className="hidden sm:block">{label}</span>
          </button>
        ))}
      </div>

      {/* Tab content */}
      {activeTab === "complexity" && <ComplexityTab data={report.cyclomatic_complexity} />}
      {activeTab === "similarity" && <SimilarityTab data={report.similarity_matrix} />}
      {activeTab === "time" && <TimeTab data={report.time_complexity} />}
      {activeTab === "practices" && <PracticesTab data={report.bad_practices} />}
      {activeTab === "tests" && <TestsTab data={report.test_coverage} />}
    </div>
  );
}
