"use client";

import { useState } from "react";
import { CheckCircle2, X, BarChart3, Copy, Gauge, Shield, Download, LayoutDashboard } from "lucide-react";
import { AnalysisReport } from "../../types/analysis";
import SummaryPanel from "./SummaryPanel";
import ComplexityTab from "./ComplexityTab";
import DuplicatesTab from "./DuplicatesTab";
import MaintainabilityTab from "./MaintainabilityTab";
import PracticesTab from "./PracticesTab";

type Tab = "overview" | "complexity" | "duplicates" | "maintainability" | "practices";

const TABS: { id: Tab; label: string; Icon: React.ElementType }[] = [
  { id: "overview", label: "Overview", Icon: LayoutDashboard },
  { id: "complexity", label: "Complexity", Icon: BarChart3 },
  { id: "duplicates", label: "Duplicates", Icon: Copy },
  { id: "maintainability", label: "Maintainability", Icon: Gauge },
  { id: "practices", label: "Bad Practices", Icon: Shield },
];

function base(path: string) {
  return path.split("/").pop() ?? path;
}

function generateMarkdownReport(report: AnalysisReport): string {
  const date = new Date().toISOString().split("T")[0];
  const s = report.summary;
  const h = s.health_score;

  const lines: string[] = [
    `# CodeAnalysis Report`,
    `**Repository:** ${s.repository_name}`,
    `**Generated:** ${date}`,
    ``,
    `## Overall Repository Health`,
    `**Health Score: ${h.score}/100 (Grade ${h.grade})**`,
    ``,
    `| Component | Score | Weight |`,
    `|-----------|-------|--------|`,
    `| Maintainability | ${h.components.maintainability} | ${Math.round(h.weights.maintainability * 100)}% |`,
    `| Complexity | ${h.components.complexity} | ${Math.round(h.weights.complexity * 100)}% |`,
    `| Duplication | ${h.components.duplication} | ${Math.round(h.weights.duplication * 100)}% |`,
    ``,
    `## Summary`,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Python files | ${s.python_files} |`,
    `| Lines of code | ${s.lines_of_code} |`,
    `| Total functions | ${s.total_functions} |`,
    `| Total classes | ${s.total_classes} |`,
    `| Average cyclomatic complexity | ${s.average_complexity} |`,
    `| Duplicate code | ${s.duplication_percentage}% |`,
    `| Average maintainability index | ${s.average_maintainability} |`,
    ``,
    `---`,
    ``,
    `## 1. Cyclomatic Complexity`,
    `Average CC **${report.complexity.average_complexity}** across ${report.complexity.function_count} functions.`,
    ``,
  ];

  if (report.complexity.high_risk_functions.length) {
    lines.push(`### High-risk functions (CC > 10)`, ``, `| Function | File | CC | Line |`, `|----------|------|----|------|`);
    for (const fn of report.complexity.high_risk_functions) {
      lines.push(`| \`${fn.name}\` | ${base(fn.file_path)} | ${fn.complexity} | ${fn.lineno} |`);
    }
  } else {
    lines.push(`_No high-risk functions._`);
  }

  lines.push(``, `---`, ``, `## 2. Duplicate Code Detection (Winnowing)`,
    `Overall duplication: **${report.duplication.duplication_percentage}%** (${report.duplication.duplicated_lines}/${report.duplication.total_lines} lines).`, ``);
  if (report.duplication.duplicate_pairs.length) {
    lines.push(`| File A | File B | Similarity | Duplicate ranges (A) |`, `|--------|--------|-----------|----------------------|`);
    for (const p of report.duplication.duplicate_pairs) {
      const ranges = p.blocks_a.map((b) => `${b.start}-${b.end}`).join(", ") || "—";
      lines.push(`| \`${base(p.file_a)}\` | \`${base(p.file_b)}\` | ${p.similarity}% | ${ranges} |`);
    }
  } else {
    lines.push(`_No significant duplication detected._`);
  }

  lines.push(``, `---`, ``, `## 3. Maintainability (Halstead + MI)`,
    `Average Maintainability Index: **${report.maintainability.average_maintainability}** (${report.maintainability.rating}).`, ``);
  if (report.maintainability.lowest_files.length) {
    lines.push(`### Lowest-maintainability files`, ``, `| File | MI | Rating |`, `|------|----|--------|`);
    for (const f of report.maintainability.lowest_files) {
      lines.push(`| \`${base(f.file_path)}\` | ${f.maintainability_index} | ${f.rating} |`);
    }
  }

  lines.push(``, `---`, ``, `## Bad Practices (auxiliary)`, ``);
  const filesWithIssues = report.bad_practices.filter((f) => f.issues.length);
  if (filesWithIssues.length) {
    for (const file of filesWithIssues) {
      lines.push(`### ${base(file.file_path)}`, `| Line | Type | Message |`, `|------|------|---------|`);
      for (const issue of file.issues) {
        lines.push(`| L${issue.line} | \`${issue.type}\` | ${issue.message} |`);
      }
      lines.push(``);
    }
  } else {
    lines.push(`No bad practices detected.`);
  }

  lines.push(``, `---`, `_Generated by CodeAnalysis_`);
  return lines.join("\n");
}

function downloadFile(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

interface Props {
  repoName: string;
  report: AnalysisReport;
  onClose: () => void;
}

export default function ReportViewer({ repoName, report, onClose }: Props) {
  const [activeTab, setActiveTab] = useState<Tab>("overview");

  const handleDownload = () => {
    const md = generateMarkdownReport(report);
    downloadFile(md, `${repoName}-analysis.md`, "text/markdown");
  };

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex items-center gap-3 p-4 rounded-xl bg-slate-900/60 border border-slate-800">
        <CheckCircle2 className="w-5 h-5 text-green-400 shrink-0" />
        <div className="min-w-0 flex-1">
          <p className="font-semibold text-white truncate">{repoName}</p>
          <p className="text-xs text-slate-500">
            {report.summary.python_files} file(s) · Health {report.summary.health_score.score}/100
          </p>
        </div>
        <button
          onClick={handleDownload}
          title="Download Markdown report"
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm bg-indigo-600 hover:bg-indigo-500 text-white transition-colors"
        >
          <Download className="w-3.5 h-3.5" />
          <span className="hidden sm:block">Report</span>
        </button>
        <button
          onClick={onClose}
          className="p-1.5 rounded-lg text-slate-500 hover:text-slate-300 hover:bg-slate-800 transition-colors"
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 p-1 bg-slate-900 rounded-xl border border-slate-800 overflow-x-auto">
        {TABS.map(({ id, label, Icon }) => (
          <button
            key={id}
            onClick={() => setActiveTab(id)}
            className={[
              "flex-1 flex items-center justify-center gap-1.5 py-2 px-3 rounded-lg text-sm font-medium transition-all whitespace-nowrap",
              activeTab === id ? "bg-indigo-600 text-white shadow" : "text-slate-400 hover:text-slate-200",
            ].join(" ")}
          >
            <Icon className="w-3.5 h-3.5" />
            <span className="hidden sm:block">{label}</span>
          </button>
        ))}
      </div>

      {/* Tab content */}
      {activeTab === "overview" && <SummaryPanel summary={report.summary} />}
      {activeTab === "complexity" && <ComplexityTab data={report.complexity} />}
      {activeTab === "duplicates" && <DuplicatesTab data={report.duplication} />}
      {activeTab === "maintainability" && <MaintainabilityTab data={report.maintainability} />}
      {activeTab === "practices" && <PracticesTab data={report.bad_practices} />}
    </div>
  );
}
